// Constants for MongoDB
export const Role = {
  VIEWER: 'VIEWER',
  ANALYST: 'ANALYST',
  ADMIN: 'ADMIN',
};

export const UserStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
};

export const TransactionType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
};

export const Category = {
  SALARY: 'SALARY',
  FREELANCE: 'FREELANCE',
  INVESTMENT: 'INVESTMENT',
  FOOD: 'FOOD',
  TRANSPORT: 'TRANSPORT',
  UTILITIES: 'UTILITIES',
  ENTERTAINMENT: 'ENTERTAINMENT',
  HEALTHCARE: 'HEALTHCARE',
  SHOPPING: 'SHOPPING',
  EDUCATION: 'EDUCATION',
  TRAVEL: 'TRAVEL',
  OTHER: 'OTHER',
};

export const EventAction = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_UPDATED: 'TRANSACTION_UPDATED',
  TRANSACTION_DELETED: 'TRANSACTION_DELETED',
  TRANSACTION_RESTORED: 'TRANSACTION_RESTORED',
  ANOMALY_DETECTED: 'ANOMALY_DETECTED',
  INSIGHT_GENERATED: 'INSIGHT_GENERATED',
  HEALTH_SCORE_CALCULATED: 'HEALTH_SCORE_CALCULATED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  VIEW_AS_ACTIVATED: 'VIEW_AS_ACTIVATED',
};
